constants:
  file:
    upload-directory: D:\hc\upload\greengram
    feed-pic: /feed
    profile-pic: /profile

  jwt:
    issuer: green502@green.com #??? ??
    bearer-token: JWT
    claim-key: signedUser
    secret-key: DeaguGreenArtAcademyClass502MsaClassFightingkkkkkk
    access-token-cookie-name: access-token
    access-token-cookie-path: / #?? ???? ??? ???
    access-token-cookie-validity-seconds: 900 # 15?(s) 60 * 15

    access-token-validity-milliseconds: 900_000 #15? (ms) 60 * 15 *1000
    refresh-token-cookie-name: refresh-token
    refresh-token-cookie-path: /api/user/reissue #?? ???? ??? ???
    refresh-token-cookie-validity-seconds: 1_296_000 # 15? (s) 60 * 60 * 24 * 15
    refresh-token-validity-milliseconds: 1_296_000_000 # 15? (ms) 60 * 60 * 24 * 15 * 1000



spring:
  application:
    name: greengram
  datasource:
    url: jdbc:log4jdbc:mariadb://localhost/greengram
    username: root
    password: green502
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jackson:
    default-property-inclusion: non_null # 응답json 에서 null속성 확인
  jpa:
    database: mysql
    defer-datasource-initialization: true
    hibernate:
        #      ddl-auto: update #???? ??? entity? ???? create ??.
      ddl-auto: create #???? ????? ???? ?? drop ? create??.
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        format_sql: true #??? ??? ??? ? ????? ???
        order_updates: true
        show_sql: true

  servlet:
      multipart:
        max-file-size: 15MB
  sql:
    init:
      mode: always
mybatis:
  mapper-locations: mappers/**/*.xml

  configuration:
    map-underscore-to-camel-case: true